/** Worldroot — constants, classes, resources, upgrades. */

window.WorldrootConfig = {
  SAVE_KEY: 'worldroot_save_v5',
  SAVE_KEY_OFFLINE: 'worldroot_save_offline_v5',
  TICK_MS: 1000,
  OFFLINE_SPEED_MULT: 0.5,
  OFFLINE_MAX_MS: 24 * 60 * 60 * 1000,
  BASE_XP_PER_TICK: 10,
  BASE_RESOURCE_PER_TICK: 1,
  UPGRADE_BONUS_PER_LEVEL: 0.01,
  UPGRADE_FLAT_PER_LEVEL: 1,
  RATE_WINDOW_TICKS: 30,
  BASE_INVENTORY_SLOTS: 16,
  BASE_STORAGE_SLOTS: 24,
  BASE_STACK_SIZE: 10,
  STORAGE_STACK_MAX: 999999999,
  SMELT_BASE_CAPACITY: 100,
  PRODUCE_BASE_CAPACITY: 100,
  STAT_SCALE: 0.03,
  GATHER_INTERVAL_TICKS: 5,
  GATHER_RATE_PER_MIN: 12,
  BASE_GATHER_EFFICIENCY: 1,
  VEIN_EFF_CURVE: [
    [1, 10],
    [50, 100],
    [250, 200],
    [1250, 300],
    [6250, 400],
  ],
  UPGRADE_MAX_LEVEL: 50,
  UPGRADE_TIER_SIZE: 5,
  UPGRADE_UNLOCK_RESOURCES: [10, 50, 150, 500, 2000, 5000, 17500, 50000, 150000, 400000],
  UPGRADE_LEVEL_GOLD: [5, 25, 75, 250, 1000, 2500, 8750, 25000, 75000, 200000],
  LEVEL_EFF_BONUS: 1,
  LEVEL_MULTI_BONUS: 0.005,
  TALENT_POINTS_PER_LEVEL: 2,
  TALENT_MAX_LEVEL: 50,

  TALENT_SKILL_MAP: {
    mining: 'gather',
    woodcutting: 'gather',
    fishing: 'gather',
    combat: 'combat',
    producing: 'producing',
    smelting: 'smelting',
  },

  TALENT_TREES: {
    combat: [
      { id: 'hp', label: 'HP', flat: 1, perLabel: '+1 HP/pt' },
      { id: 'mp', label: 'MP', flat: 1, perLabel: '+1 MP/pt' },
      { id: 'def', label: 'DEF', flat: 1, perLabel: '+1 DEF/pt' },
      { id: 'acc', label: 'ACC', flat: 1, perLabel: '+1 ACC/pt' },
      { id: 'crit_chance', label: 'Crit Chance', percent: 0.005, perLabel: '+0.5%/pt' },
      { id: 'crit_damage', label: 'Crit Damage', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'drop_rate', label: 'Drop Rate', percent: 0.0025, perLabel: '+0.25%/pt' },
      { id: 'gold_gain', label: 'Gold Gain', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'material_carry', label: 'Material Carry', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'strength', label: 'STR', flat: 1, perLabel: '+1 STR/pt' },
      { id: 'agility', label: 'AGI', flat: 1, perLabel: '+1 AGI/pt' },
      { id: 'magic', label: 'MAG', flat: 1, perLabel: '+1 MAG/pt' },
      { id: 'attack_speed', label: 'Attack Speed', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'xp', label: 'Combat XP', percent: 0.01, perLabel: '+1%/pt' },
    ],
    gather: [
      { id: 'eff', label: 'Efficiency', flat: 1, perLabel: '+1 eff/pt' },
      { id: 'carry', label: 'Carrying Capacity', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'multi', label: 'Multi Resource', percent: 0.005, perLabel: '+0.5%/pt' },
      { id: 'xp', label: 'Skill XP', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'speed', label: 'Gather Speed', percent: 0.01, perLabel: '+1%/pt' },
    ],
    producing: [
      { id: 'speed', label: 'Production Speed', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'xp', label: 'Production XP', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'multi', label: 'Multi Producing', percent: 0.005, perLabel: '+0.5%/pt' },
      { id: 'capacity', label: 'Producing Capacity', percent: 0.01, perLabel: '+1%/pt' },
    ],
    smelting: [
      { id: 'speed', label: 'Smelting Speed', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'xp', label: 'Smelting XP', percent: 0.01, perLabel: '+1%/pt' },
      { id: 'multi', label: 'Multi Smelting', percent: 0.005, perLabel: '+0.5%/pt' },
      { id: 'capacity', label: 'Smelting Capacity', percent: 0.01, perLabel: '+1%/pt' },
    ],
  },
  COMBAT_ATTACK_SEC: 1.5,
  COMBAT_RESPAWN_SEC: 10,
  BASE_CHAR_HP: 20,
  BASE_CHAR_MP: 10,
  BASE_CHAR_DAMAGE: 5,
  BASE_ACCURACY: 0,
  BASE_DROP_CHANCE: 0.2,

  SLOT_UNLOCK_AT: [0, 5, 10],
  MAX_SLOTS: 3,
  UNLOCK_LEVELS: [0, 5, 10, 15],
  SMELT_SLOT_UNLOCKS: [0, 5, 10, 15],

  SIDEBAR_NAV: [
    { type: 'section', label: 'Menu' },
    { type: 'page', id: 'characters', label: 'Characters', icon: '👥' },
    { type: 'page', id: 'inventory', label: 'Inventory', icon: '🎒' },
    { type: 'page', id: 'storage', label: 'Storage', icon: '📦' },
    { type: 'divider' },
    { type: 'section', label: 'Skills' },
    { type: 'skill', id: 'combat', label: 'Combat', icon: '🗡' },
    { type: 'skill', id: 'mining', label: 'Mining', icon: '⛏' },
    { type: 'skill', id: 'woodcutting', label: 'Woodcutting', icon: '🪓' },
    { type: 'skill', id: 'fishing', label: 'Fishing', icon: '🎣' },
    { type: 'skill', id: 'producing', label: 'Producing', icon: '🏭' },
    { type: 'skill', id: 'smelting', label: 'Smelting', icon: '🔥' },
    { type: 'skill', id: 'crafting', label: 'Crafting', icon: '🧵', comingSoon: true },
    { type: 'divider' },
    { type: 'page', id: 'worldtree', label: 'World Tree', icon: '🌳' },
    { type: 'divider' },
    { type: 'page', id: 'settings', label: 'Settings', icon: '⚙' },
  ],

  CLASSES: {
    warrior: {
      id: 'warrior', name: 'Warrior', icon: '⚔', portrait: 'warrior',
      desc: '+1 STR → +1 Mining efficiency',
      combatStat: 'strength', gatherStat: 'strength',
      baseStats: { strength: 0, agility: 0, magic: 0 },
    },
    archer: {
      id: 'archer', name: 'Archer', icon: '🏹', portrait: 'archer',
      desc: '+1 AGI → +1 Woodcutting efficiency',
      combatStat: 'agility', gatherStat: 'agility',
      baseStats: { strength: 0, agility: 0, magic: 0 },
    },
    sorcerer: {
      id: 'sorcerer', name: 'Sorcerer', icon: '✦', portrait: 'sorcerer',
      desc: '+1 MAG → +1 Fishing efficiency',
      combatStat: 'magic', gatherStat: 'magic',
      baseStats: { strength: 0, agility: 0, magic: 0 },
    },
  },

  SKILLS: {
    combat: { id: 'combat', name: 'Combat', activity: 'combat', icon: '🗡', desc: 'Hunt monsters for XP and loot' },
    mining: { id: 'mining', name: 'Mining', activity: 'mining', icon: '⛏', desc: 'Mine ore from the deep roots', gatherStat: 'strength' },
    woodcutting: { id: 'woodcutting', name: 'Woodcutting', activity: 'woodcutting', icon: '🪓', desc: 'Chop timber from wild groves', gatherStat: 'agility' },
    fishing: { id: 'fishing', name: 'Fishing', activity: 'fishing', icon: '🎣', desc: 'Catch fish from forest streams', gatherStat: 'magic' },
    producing: { id: 'producing', name: 'Producing', icon: '🏭', desc: 'Passively craft supplies — collect into inventory' },
    smelting: { id: 'smelting', name: 'Smelting', icon: '🔥', desc: 'Smelt ore into bars' },
    crafting: { id: 'crafting', name: 'Crafting', icon: '🧵', desc: 'Craft gear and tools', comingSoon: true },
  },

  VEINS: {
    mining: [
      { id: 'copper_vein', name: 'Copper Vein', resource: 'copper', minLevel: 0, icon: 'copper_vein', xp: 5 },
      { id: 'iron_vein', name: 'Iron Vein', resource: 'iron', minLevel: 10, icon: 'iron_vein', xp: 15 },
      { id: 'gold_vein', name: 'Gold Vein', resource: 'gold', minLevel: 20, icon: 'gold_vein', xp: 25 },
      { id: 'platinum_vein', name: 'Platinum Vein', resource: 'platinum', minLevel: 30, icon: 'platinum_vein', xp: 50 },
    ],
    woodcutting: [
      { id: 'oak_grove', name: 'Oak Grove', resource: 'oak', minLevel: 0, icon: 'oak_grove', xp: 5 },
      { id: 'spruce_grove', name: 'Spruce Grove', resource: 'spruce', minLevel: 10, icon: 'spruce_grove', xp: 15 },
      { id: 'birch_grove', name: 'Birch Grove', resource: 'birch', minLevel: 20, icon: 'birch_grove', xp: 25 },
      { id: 'jungle_grove', name: 'Jungle Grove', resource: 'jungle', minLevel: 30, icon: 'jungle_grove', xp: 50 },
    ],
    fishing: [
      { id: 'shrimp_spot', name: 'Shrimp Spot', resource: 'shrimp', minLevel: 0, icon: 'shrimp', xp: 5 },
      { id: 'trout_spot', name: 'Trout Spot', resource: 'trout', minLevel: 10, icon: 'trout', xp: 15 },
      { id: 'salmon_spot', name: 'Salmon Spot', resource: 'salmon', minLevel: 20, icon: 'salmon', xp: 25 },
      { id: 'lobster_spot', name: 'Lobster Spot', resource: 'lobster', minLevel: 30, icon: 'lobster', xp: 50 },
    ],
  },

  MONSTERS: [
    { id: 'forest_slime', name: 'Forest Slime', level: 0, hp: 25, damage: 2, xp: 5, accuracy: 0, goldMin: 1, goldMax: 3, drop: { id: 'slime_gel', name: 'Ectoplasm', amount: 1 } },
    { id: 'will_o_wisp', name: 'Will-O-Wisp', level: 10, hp: 100, damage: 5, xp: 15, accuracy: 5, goldMin: 3, goldMax: 6, drop: { id: 'wisp_essence', name: 'Wisp Essence', amount: 1 } },
    { id: 'gloomcap', name: 'Gloomcap', level: 20, hp: 250, damage: 10, xp: 25, accuracy: 10, goldMin: 5, goldMax: 10, drop: { id: 'gloomspore', name: 'Gloomspore', amount: 1 } },
    { id: 'spore_bat', name: 'Spore Bat', level: 30, hp: 450, damage: 20, xp: 50, accuracy: 15, goldMin: 8, goldMax: 15, drop: { id: 'bat_wing_membrane', name: 'Bat Wing Membrane', amount: 1 } },
  ],

  SMELT_RECIPES: [
    { ore: 'copper', bar: 'copper_bar', name: 'Copper Bar', orePerBar: 2, ticks: 15, xp: 5 },
    { ore: 'iron', bar: 'iron_bar', name: 'Iron Bar', orePerBar: 4, ticks: 30, xp: 15 },
    { ore: 'gold', bar: 'gold_bar', name: 'Gold Bar', orePerBar: 8, ticks: 60, xp: 25 },
    { ore: 'platinum', bar: 'platinum_bar', name: 'Platinum Bar', orePerBar: 16, ticks: 120, xp: 50 },
  ],

  PRODUCE_SLOTS: [
    { slot: 0, id: 'twine', name: 'Twine', minLevel: 0, ticks: 30, xp: 5 },
    { slot: 1, id: 'wooden_pegs', name: 'Wooden Pegs', minLevel: 5, ticks: 60, xp: 15 },
    { slot: 2, id: 'iron_nails', name: 'Iron Nails', minLevel: 10, ticks: 120, xp: 25 },
    { slot: 3, id: 'resin', name: 'Resin', minLevel: 15, ticks: 240, xp: 50 },
  ],

  ACTIVITIES: [
    { id: 'mining', label: 'Mining', skill: 'mining' },
    { id: 'woodcutting', label: 'Woodcutting', skill: 'woodcutting' },
    { id: 'fishing', label: 'Fishing', skill: 'fishing' },
    { id: 'combat', label: 'Combat', skill: 'combat' },
  ],

  RESOURCE_IDS: [
    'copper', 'iron', 'gold', 'platinum',
    'copper_bar', 'iron_bar', 'gold_bar', 'platinum_bar',
    'oak', 'spruce', 'birch', 'jungle',
    'shrimp', 'trout', 'salmon', 'lobster',
    'slime_gel', 'wisp_essence', 'gloomspore', 'bat_wing_membrane',
    'twine', 'wooden_pegs', 'iron_nails', 'resin',
  ],

  RESOURCE_NAMES: {
    copper: 'Copper Ore', iron: 'Iron Ore', gold: 'Gold Ore', platinum: 'Platinum Ore',
    copper_bar: 'Copper Bar', iron_bar: 'Iron Bar', gold_bar: 'Gold Bar', platinum_bar: 'Platinum Bar',
    oak: 'Oak Log', spruce: 'Spruce Log', birch: 'Birch Log', jungle: 'Jungle Log',
    shrimp: 'Shrimp', trout: 'Trout', salmon: 'Salmon', lobster: 'Lobster',
    slime_gel: 'Ectoplasm', wisp_essence: 'Wisp Essence', gloomspore: 'Gloomspore', bat_wing_membrane: 'Bat Wing Membrane',
    twine: 'Twine', wooden_pegs: 'Wooden Pegs', iron_nails: 'Iron Nails', resin: 'Resin',
  },

  ICON_BASE: 'assets/icons',
  PORTRAIT_BASE: 'assets/characters',
  GAME_ICONS: {
    forest_slime: 'forest_slime', will_o_wisp: 'will_o_wisp', gloomcap: 'gloomcap', spore_bat: 'spore_bat',
    slime_gel: 'slime_gel', wisp_essence: 'wisp_essence', gloomspore: 'gloomspore', bat_wing_membrane: 'bat_wing_membrane',
    copper: 'copper', iron: 'iron', gold: 'gold', platinum: 'platinum',
    copper_bar: 'copper_bar', iron_bar: 'iron_bar', gold_bar: 'gold_bar', platinum_bar: 'platinum_bar',
    copper_vein: 'copper_vein', iron_vein: 'iron_vein', gold_vein: 'gold_vein', platinum_vein: 'platinum_vein',
    oak: 'oak', spruce: 'spruce', birch: 'birch', jungle: 'jungle',
    oak_grove: 'oak_grove', spruce_grove: 'spruce_grove', birch_grove: 'birch_grove', jungle_grove: 'jungle_grove',
    shrimp: 'shrimp', trout: 'trout', salmon: 'salmon', lobster: 'lobster',
    twine: 'twine', wooden_pegs: 'wooden_pegs', iron_nails: 'iron_nails', resin: 'resin',
  },

  CARRY_EFFECT_BY_SKILL: {
    mining: 'mining_carry',
    woodcutting: 'woodcutting_carry',
    fishing: 'fishing_carry',
    combat: 'carry_capacity',
  },

  WORLD_TREE_BRANCHES: [
    {
      id: 'combat', name: 'Combat Branch', icon: '⚔',
      nodes: [
        { id: 'base_hp', name: '+ Base HP', effect: 'base_hp', bonusType: 'flat', desc: 'Increases base hit points', costRes: 'oak', baseCost: 15 },
        { id: 'base_mp', name: '+ Base MP', effect: 'base_mp', bonusType: 'flat', desc: 'Increases base mana', costRes: 'copper', baseCost: 15 },
        { id: 'base_damage', name: '+ Base Damage', effect: 'base_damage', bonusType: 'flat', desc: 'Increases base damage', costRes: 'slime_gel', baseCost: 20 },
        { id: 'pct_damage', name: '+% Damage', effect: 'pct_damage', bonusType: 'percent', desc: 'Increases damage dealt', costRes: 'gold', baseCost: 30 },
        { id: 'base_accuracy', name: '+ Base Accuracy', effect: 'base_accuracy', bonusType: 'flat', desc: 'Increases hit accuracy', costRes: 'twine', baseCost: 25 },
        { id: 'base_defence', name: '+ Base Defence', effect: 'base_defence', bonusType: 'flat', desc: 'Increases base defence', costRes: 'iron', baseCost: 20 },
        { id: 'crit_damage', name: '+% Crit Damage', effect: 'crit_damage', bonusType: 'percent', desc: 'Increases critical damage', costRes: 'wooden_pegs', baseCost: 30 },
        { id: 'crit_chance', name: '+% Crit Chance', effect: 'crit_chance', bonusType: 'percent', desc: 'Increases critical chance', costRes: 'bat_wing_membrane', baseCost: 30 },
        { id: 'drop_rate', name: '+% Drop Rate', effect: 'drop_rate', bonusType: 'percent', desc: 'Increases loot drop rate', costRes: 'platinum_bar', baseCost: 25 },
        { id: 'strength', name: '+ Strength', effect: 'strength', bonusType: 'flat', desc: 'Increases strength', costRes: 'spruce', baseCost: 25 },
        { id: 'agility', name: '+ Agility', effect: 'agility', bonusType: 'flat', desc: 'Increases agility', costRes: 'trout', baseCost: 25 },
        { id: 'magic', name: '+ Magic', effect: 'magic', bonusType: 'flat', desc: 'Increases magic', costRes: 'platinum', baseCost: 25 },
        { id: 'carry_capacity', name: '+% Carrying Capacity', effect: 'carry_capacity', bonusType: 'percent', desc: 'More items per inventory slot', costRes: 'copper_bar', baseCost: 30 },
        { id: 'gold_gain', name: '+% Gold Gain', effect: 'gold_gain', bonusType: 'percent', desc: 'Earn more gold', costRes: 'resin', baseCost: 20 },
        { id: 'multikill_rate', name: '+% Base Multikill Rate', effect: 'multikill_rate', bonusType: 'percent', desc: 'Chance for bonus drops across all skills', costRes: 'leech_sucker', baseCost: 25 },
        { id: 'all_skill_eff', name: '+ All Skill Efficiency', effect: 'all_skill_eff', bonusType: 'flat', desc: 'Bonus efficiency for mining, woodcutting, and fishing', costRes: 'moth_pollen', baseCost: 25 },
      ],
    },
    {
      id: 'mining', name: 'Mining Branch', icon: '⛏',
      nodes: [
        { id: 'base_mining_eff', name: '+ Base Mining Efficiency', effect: 'mining_yield', bonusType: 'flat', desc: 'Mine more ore per action', costRes: 'oak', baseCost: 30 },
        { id: 'mining_carry', name: '+% Carrying Capacity', effect: 'mining_carry', bonusType: 'percent', desc: 'More ore per inventory slot', costRes: 'trout', baseCost: 25 },
        { id: 'multi_ore', name: '+% Multi-Ore Chance', effect: 'mining_multi', bonusType: 'percent', desc: 'Chance for extra ore', costRes: 'gloomspore', baseCost: 35 },
        { id: 'mining_xp', name: '+% Mining Exp Gain', effect: 'mining_xp', bonusType: 'percent', desc: 'More mining XP', costRes: 'wooden_pegs', baseCost: 30 },
      ],
    },
    {
      id: 'woodcutting', name: 'Woodcutting Branch', icon: '🪓',
      nodes: [
        { id: 'base_wc_eff', name: '+ Base Woodcutting Efficiency', effect: 'woodcutting_yield', bonusType: 'flat', desc: 'Chop more logs per action', costRes: 'shrimp', baseCost: 30 },
        { id: 'wc_carry', name: '+% Carrying Capacity', effect: 'woodcutting_carry', bonusType: 'percent', desc: 'More logs per inventory slot', costRes: 'iron', baseCost: 25 },
        { id: 'multi_log', name: '+% Multi-Log Chance', effect: 'woodcutting_multi', bonusType: 'percent', desc: 'Chance for extra logs', costRes: 'iron_nails', baseCost: 35 },
        { id: 'wc_xp', name: '+% Woodcutting Exp Gain', effect: 'woodcutting_xp', bonusType: 'percent', desc: 'More woodcutting XP', costRes: 'iron_bar', baseCost: 30 },
      ],
    },
    {
      id: 'fishing', name: 'Fishing Branch', icon: '🎣',
      nodes: [
        { id: 'base_fish_eff', name: '+ Base Fishing Efficiency', effect: 'fishing_yield', bonusType: 'flat', desc: 'Catch more fish per action', costRes: 'copper', baseCost: 30 },
        { id: 'fish_carry', name: '+% Carrying Capacity', effect: 'fishing_carry', bonusType: 'percent', desc: 'More fish per inventory slot', costRes: 'spruce', baseCost: 25 },
        { id: 'multi_fish', name: '+% Multi-Catch Chance', effect: 'fishing_multi', bonusType: 'percent', desc: 'Chance for extra fish', costRes: 'gold_bar', baseCost: 35 },
        { id: 'fish_xp', name: '+% Fishing Exp Gain', effect: 'fishing_xp', bonusType: 'percent', desc: 'More fishing XP', costRes: 'wisp_essence', baseCost: 30 },
      ],
    },
    {
      id: 'utility', name: 'Utility Branch', icon: '✦',
      nodes: [
        { id: 'smelt_speed', name: '+% Smelting Speed', effect: 'smelt_speed', bonusType: 'percent', desc: 'Smelt ore faster', costRes: 'slime_gel', baseCost: 25 },
        { id: 'produce_speed', name: '+% Producing Speed', effect: 'produce_speed', bonusType: 'percent', desc: 'Produce items faster', costRes: 'shrimp', baseCost: 25 },
        { id: 'smelt_xp', name: '+% Smelting Exp', effect: 'smelt_xp', bonusType: 'percent', desc: 'More smelting XP', costRes: 'birch', baseCost: 30 },
        { id: 'produce_xp', name: '+% Producing Exp', effect: 'produce_xp', bonusType: 'percent', desc: 'More producing XP', costRes: 'salmon', baseCost: 30 },
        { id: 'multi_smelt', name: '+% Multi Smelting', effect: 'smelt_multi', bonusType: 'percent', desc: 'Chance for extra bars', costRes: 'lobster', baseCost: 35 },
        { id: 'multi_produce', name: '+% Multi Producing', effect: 'produce_multi', bonusType: 'percent', desc: 'Chance for extra products', costRes: 'jungle', baseCost: 35 },
        { id: 'smelt_capacity', name: '+% Smelting Capacity', effect: 'smelt_capacity', bonusType: 'percent', desc: 'Extra smelting throughput', costRes: 'twine', baseCost: 30 },
        { id: 'produce_capacity', name: '+% Producing Capacity', effect: 'produce_capacity', bonusType: 'percent', desc: 'Extra producing throughput', costRes: 'copper_bar', baseCost: 30 },
      ],
    },
  ],
};
